---
- name: Deploy MiCADO master
  hosts: micado
  gather_facts: False

  pre_tasks:
  - name: (Ansible) Include pre-tasks
    include_tasks: "{{ task_item }}"
    loop: "{{ query('fileglob', \"pre-task/[0-9][0-9]*.yml\")|sort }}"
    loop_control:
      loop_var: task_item
    tags:
    - always

  roles:
    - role: micado_master/build
      tags:
      - build
    - role: micado_master/start
      tags:
      - start

  vars:

    ######################################################################
    ##### If you want to change the configuration, please edit here. #####
    ######################################################################

    - cloud_cred_path: ./credentials-cloud-api.yml
    - gce_cred_path: ./credentials-gce.json
    - oci_key_path: ./credentials-oci-key.pem
    - docker_cred_path: ./credentials-docker-registry.yml
    - micado_cred_path: ./credentials-micado.yml
    - micado_version: v0.9.1

    - disable_optimizer: True
    - disable_worker_updates: True
    - grafana_admin_pwd: secret
    - web_listening_port: 443
    - web_session_timeout: 600

    - master_hostname: micado-master
    - worker_hostname: micado-worker

    # At least one cloud orchestrator must be enabled
    - enable_occopus: False
    - enable_terraform: True

    ##################################################################################
    ##### Please do not edit under this line unless you know what you are doing. #####
    ##################################################################################

    - intel_cpu: false
    - oci_key: '{{ lookup("file", "{{ oci_key_path }}") }}'
    - docker_images:
        alertmanager: prom/alertmanager:v0.21.0
        cadvisor: gcr.io/google-containers/cadvisor:v0.36.0
        credential_manager: micado/credential-manager:v0.9.1-slim
        crypto_engine: micado/crypto-engine:v0.9.1-slim
        dashboard: micado/dashboard:0.4.0
        grafana: grafana/grafana:7.1.5
        iivr: micado/iivr:v0.9.1-slim
        node_exporter: prom/node-exporter:v1.0.1
        occopus: micado/occopus:1.7-rc6
        optimizer: micado/optimizer:v0.9.1
        policykeeper: micado/policykeeper:v0.9.1-slim
        prometheus: prom/prometheus:v2.20.1
        redis: redis:5-alpine
        securitypolicymanager: micado/security-policy-manager:v0.9.1-slim
        terraform: hashicorp/terraform:0.12.29
        toscasubmitter: micado/toscasubmitter:alpine
        vault: vault:1.5.3
        zorp: micado/zorpgpl:6.0.12

    - packages:
        docker_ce: "docker-ce=5:19.03.12~3-0~ubuntu-{{ ansible_distribution_release }}"
        docker_ce_cli: "docker-ce-cli=5:19.03.12~3-0~ubuntu-{{ ansible_distribution_release }}"
        containerd_io: containerd.io=1.2.13-2
        kubernetes_version: 1.19.0-00
